# Generated by Django 5.0.6 on 2024-07-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(default='Help with questions in the chat.')),
                ('gpt_model', models.TextField(default='gpt-3.5-turbo')),
                ('max_messages', models.IntegerField(default=10)),
                ('telegram_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.gptresponse')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='admins',
            field=models.ManyToManyField(to='telegram.telegramuser'),
        ),
    ]
